name: Release Fastwin
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Publish Native AOT
        run: dotnet publish -r win-${{ matrix.arch }} -c Release /p:PublishAot=true -o ./publish
      - name: Rename Binary
        shell: pwsh
        run: Move-Item ./publish/Fastwin.exe ./publish/FastWin-${{ matrix.arch }}.exe
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fastwin-${{ matrix.arch }}
          path: ./publish/fastwin-${{ matrix.arch }}.exe
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: fastwin Release ${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            ./artifacts/fastwin-x64/fastwin-x64.exe
            ./artifacts/fastwin-arm64/fastwin-arm64.exe
